delete from khren
delete from khzl
delete from xmzl
delete from htping
delete from htping1
delete from yongjin
delete from fyd
delete from fybx
delete from xunjiaD
delete from xunjiaMx
delete from xunjiawb
delete from newfuwu
delete from qmrz
delete from baojiaD
delete from baojiaMx
delete from pldmain
delete from pld
